### ISSUE TITLE
Can two real world datasets be run through with the given code?

### ISSUE THREAD

**Issue by head-bigandhard** [mateuszwilinski/dynamic-message-passing#15]
Hello，I read your paper and want to do the same experiments. Can two real world datasets be run through with the given codes?

**Comment by mateuszwilinski** [comment]
Hi,

not sure if I understand the question, but you can run any network with this code. Hope it helps and please let me know if you have any other questions.

Best,
Mateusz

**Comment by head-bigandhard** [comment]
Hi，thank you for your reply.
I really want to run codes with two real-word datesets in the paper. Could you upload them？ Thank you！

**Comment by mateuszwilinski** [comment]
I don't keep data in repos, but if you send me your email, I can send you the data. Or you can directly download them from the source, which is given in the paper.

Best,
Mateusz

**Comment by head-bigandhard** [comment]
I tried to download from the data source given in the article, but failed. My email is sty2664515426@163.com. Thank you for your reply.

**Comment by head-bigandhard** [comment]
Hi，I have sent my email address to you. When do you share the two real-world datesets in paper to me? Thank you!

**Comment by mateuszwilinski** [comment]
Hi, I sent the dataset to your email. Hope it helps!
